

' This file contains the PRU instructions in a FB array which are  
' to be downloaded from the host CPU to the PRU instruction memory.
' This file is generated by the PRU assembler.                     

STATIC SHARED AS UINTEGER Pru_Init(...) = { _
  &H91042480, _
  &H1d04e0e0, _
  &H81042480, _
  &H2444e1c1, _
  &H24080081, _
  &H240100e2, _
  &Hf1000103, _
  &He1000203, _
  &H0104e1e1, _
  &H0101e2e2, _
  &H776d02fc, _
  &H240040e1, _
  &H240002ea, _
  &H240000e0, _
  &H0103e2e2, _
  &H11fc0202, _
  &He1042082, _
  &Hf1006183, _
  &He1042180, _
  &H2eff8985, _
  &Hf1002488, _
  &H5102e80b, _
  &He100248a, _
  &H0101e9e9, _
  &Hf1002486, _
  &H50eae607, _
  &H4f1029fd, _
  &H24ffffc5, _
  &H24ffff85, _
  &He1342385, _
  &He10c2185, _
  &H21002300, _
  &Hf1342385, _
  &H1d08e3e7, _
  &Hf12c6786, _
  &He3006284, _
  &H0118e2e2, _
  &H0120e1e1, _
  &H77a001eb, _
  &H2444e0d4, _
  &H24d00094, _
  &Hf1003483, _
  &H6900e30c, _
  &H2444e0c9, _
  &H2404bc89, _
  &H240002e8, _
  &He1000908, _
  &H240000e5, _
  &Hf1003484, _
  &H6900e403, _
  &H0101e5e5, _
  &H671025fd, _
  &He100a283, _
  &H21003e00, _
  &Hf704b484, _
  &He700e283, _
  &Hf740f483, _
  &He740e283, _
  &Hf780f483, _
  &He780e283, _
  &Hf5c03483, _
  &He5c02283, _
  &H24ffffc1, _
  &H24ffff81, _
  &He1002081, _
  &H2400291f, _
  &H2a000000 }

