

' This file contains the PRU instructions in a FB array which are  
' to be downloaded from the host CPU to the PRU instruction memory.
' This file is generated by the PRU assembler.                     

STATIC SHARED AS UINTEGER Pru_Exit(...) = { _
  &H91042480, _
  &H1d04e0e0, _
  &H81042480, _
  &H2444e1c1, _
  &H24080081, _
  &H240000e0, _
  &Hf1042082, _
  &H5100e224, _
  &Hf1000203, _
  &He1000103, _
  &H0104e1e1, _
  &H0101e2e2, _
  &H776d02fc, _
  &H0103e2e2, _
  &H11fc0202, _
  &H240040e1, _
  &Hf1002183, _
  &H1d08e3e4, _
  &Hf3006285, _
  &H6902e903, _
  &He1342386, _
  &He12c6487, _
  &He1002589, _
  &H0118e2e2, _
  &H0120e1e1, _
  &H77a0e1f7, _
  &H2444e0c1, _
  &H24d00081, _
  &Hf1002283, _
  &H5100e30e, _
  &Hf1442183, _
  &Hd705e3ff, _
  &H240004e3, _
  &He1402183, _
  &Hf7a4e283, _
  &He7a4e183, _
  &Hf764e283, _
  &He764e183, _
  &Hf724e283, _
  &He724e183, _
  &Hf1102283, _
  &He1102183, _
  &H21002f00, _
  &H2444e0c4, _
  &H2404bc84, _
  &H240000e3, _
  &He1000403, _
  &H24ffffc1, _
  &H24fffe81, _
  &He1002081, _
  &H2400291f, _
  &H2a000000 }

